In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
from sklearn.datasets.california_housing import fetch_california_housing
housing = fetch_california_housing()
print(housing.DESCR)

C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\1\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block
        - HouseAge      median house age in block
        - AveRooms      average number of rooms
        - AveBedrms     average number of bedrooms
        - Population    block population
        - AveOccup      average house occupancy
        - Latitude      house block latitude
        - Longitude     house block longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
http://lib.stat.cmu.edu/datasets/

The target variable is the median house value for California districts.

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bur

In [9]:
housing.data.shape

(20640, 8)

In [12]:
housing.data[0:5], housing.target[0:5]

(array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
          1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
          3.78800000e+01, -1.22230000e+02],
        [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
          9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
          3.78600000e+01, -1.22220000e+02],
        [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
          1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
          3.78500000e+01, -1.22240000e+02],
        [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
          1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
          3.78500000e+01, -1.22250000e+02],
        [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
          1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
          3.78500000e+01, -1.22250000e+02]]),
 array([4.526, 3.585, 3.521, 3.413, 3.422]))

In [19]:
# 数据预处理（标准化）
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler()
x_data_standa = x_std.fit_transform(housing.data)

y_std = StandardScaler()
y_data_standa = y_std.fit_transform(housing.target.reshape(-1, 1))

In [20]:
# 切分数据集
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data_standa, y_data_standa)

In [21]:
# 决策树
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [25]:
# 预测
y_predict = dtr.predict(x_test)
y_predict_actual = y_std.inverse_transform(y_predict)
y_predict_actual

array([3.   , 0.775, 1.144, ..., 3.35 , 2.105, 2.713])

In [30]:
# 准确率
from sklearn.metrics import mean_squared_error
print('房价预测准确率为：', dtr.score(x_test, y_test))
print('均方误差为：', mean_squared_error(y_test, y_predict))

房价预测准确率为： 0.5787024833915568
均方误差为： 0.4185180798596444


#### 随机森林

In [34]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()

#### 网格搜索

In [43]:
from sklearn.model_selection import GridSearchCV

param = {"n_estimators": [10, 12], "max_depth": [10, 12, 15]}
gc = GridSearchCV(rf, param_grid=param, cv=5)

In [44]:
gc.fit(x_train, y_train.ravel())

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [10, 12, 15], 'n_e

In [45]:
# 准确率
print('房价预测准确率为：', gc.score(x_test, y_test))
print('均方误差为：', mean_squared_error(y_test, y_predict))
print("选取的模型为：", gc.best_params_)

房价预测准确率为： 0.7715985142372541
均方误差为： 0.4185180798596444
选取的模型为： {'max_depth': 15, 'n_estimators': 12}
